spring:
  application:
    name: job-portal-api
  datasource:
    url: jdbc:postgresql://localhost:5432/job-portal-api
    username: postgres
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
