spring:
  application:
    name: job-portal-api
  datasource:
    url: jdbc:postgresql://localhost:5432/job-portal-api
    username: postgres
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    jwt:
      secret: very-secret-key-very-secret-key-very-secret-key-very-secret-key-very-secret-key-very-secret-key
      expiration: 60  # In minutes
