-- ======================
-- USERS
-- ======================
CREATE TABLE users (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       email VARCHAR(255) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       full_name VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ======================
-- ROLES
-- ======================
CREATE TABLE roles (
                       id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                            role_id INT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
                            PRIMARY KEY (user_id, role_id)
);

-- ======================
-- EMPLOYERS
-- ======================
CREATE TABLE employers (
                           id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                           company_name VARCHAR(255),
                           company_website VARCHAR(255)
);

-- ======================
-- APPLICANTS
-- ======================
CREATE TABLE applicants (
                            id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                            resume_link TEXT,
                            bio TEXT
);

-- ======================
-- JOBS
-- ======================
CREATE TABLE jobs (
                      id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                      title VARCHAR(255) NOT NULL,
                      description TEXT NOT NULL,
                      location VARCHAR(255),
                      salary_min INTEGER,
                      salary_max INTEGER,
                      job_type VARCHAR NOT NULL CHECK (job_type IN ('FULL_TIME', 'PART_TIME', 'INTERN', 'FREELANCE', 'CONTRACT')),
                      posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                      employer_id BIGINT NOT NULL REFERENCES employers(id) ON DELETE CASCADE,
                      UNIQUE (title, location, employer_id, posted_at)
);

CREATE INDEX idx_jobs_employer_id ON jobs(employer_id);

-- ======================
-- APPLICATIONS
-- ======================
CREATE TABLE applications (
                              id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                              applicant_id BIGINT NOT NULL REFERENCES applicants(id) ON DELETE CASCADE,
                              job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                              cover_letter TEXT,
                              resume_link TEXT,
                              status VARCHAR DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'REJECTED', 'ACCEPTED')),
                              applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              UNIQUE (applicant_id, job_id)
);

CREATE INDEX idx_applications_applicant_id ON applications(applicant_id);
CREATE INDEX idx_applications_job_id ON applications(job_id);

-- ======================
-- AUDIT TABLES / LOGGING
-- ======================
CREATE TABLE job_views (
                           id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           job_id BIGINT NOT NULL REFERENCES jobs(id) ON DELETE CASCADE,
                           user_id BIGINT REFERENCES users(id),
                           viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                           UNIQUE (job_id, user_id, viewed_at)
);

CREATE INDEX idx_job_views_job_id ON job_views(job_id);
CREATE INDEX idx_job_views_user_id ON job_views(user_id);
